### PR TITLE
Julie Breakfast Ingredients

### PR DESCRIPTION
**Pull request by chewpp**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

@asergian may you pls review the ingredients I added? I think these are the perfect components for the fluffiest pancakes in the world!!!

### CODE REVIEW

**Comment by simonesept** [comment]
Hey @chewpp can you please fill in the details for objective, changes made, etc.? :) thanks!

**Comment by chewpp** [comment]
> Hey @chewpp can you please fill in the details for objective, changes made, etc.? :) thanks!

Hi @simonesept !!! I edited my request to review my ingredients. PLS AND THANK YOU!

**Comment by simonesept** [comment]
> > Hey @chewpp can you please fill in the details for objective, changes made, etc.? :) thanks!
> 
> Hi @simonesept !!! I edited my request to review my ingredients. PLS AND THANK YOU!

Amazing THANK YOU so much for your quick reply and update!! These ingredients look like they will make some DELICIOUS pancakes 🥞

**Comment by asergian** [comment]
@chewpp you need to consider Jon's stated breakfast measurements in your calculations. Please advise.

**Comment by chewpp** [comment]
> @chewpp you need to consider Jon's stated breakfast measurements in your calculations. Please advise.

Message received. Will update accordingly. Many thanks.

**Comment by chewpp** [comment]
> > @chewpp you need to consider Jon's stated breakfast measurements in your calculations. Please advise.
> 
> Message received. Will update accordingly. Many thanks.

@asergian measurements have been incorporated!!!

**Pull request merged**
