### PR TITLE
Updated breakfast servings

### PR DESCRIPTION
**Pull request by asergian**
Breakfast servings updated

## 🎯 Objective

Set the stage for how much breakfast we are making

## 🛠️ Changes made

updated service size of breakfast to 18

## 👥 Who needs to review this Pull Request? 

@chewpp @livsimomoto @simonesept @imur808 @Byungwoohan

### CODE REVIEW

**Comment by simonesept** [comment]
recipe for 6! that is perfect for our team :)

**Comment by chewpp** [comment]
Interesting feedback @simonesept ... a recipe for 6 seems to be questioning the status quo

**Comment by asergian** [comment]
@chewpp Happy to schedule a call offline, but this was a directive from upper management

**Review by livsimomoto — APPROVED** [review]

**Comment by livsimomoto** [comment]
Thank you alex!

**Pull request merged**
